//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAgregacionNumerales.perfiles {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://banrep.gov.co/s3")]
    public partial class JavaExceptionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private string messageField;
        
        private string traceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Trace {
            get {
                return this.traceField;
            }
            set {
                this.traceField = value;
                this.RaisePropertyChanged("Trace");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://banrep.gov.co/s3", ConfigurationName="perfiles.ExecutePortType")]
    public interface ExecutePortType {
        
        [System.ServiceModel.OperationContractAttribute(Action="consultaPerfilesUsuarioAppl", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WebAppAgregacionNumerales.perfiles.JavaExceptionType), Action="consultaPerfilesUsuarioAppl", Name="JavaException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WebAppAgregacionNumerales.perfiles.Output consultaPerfilesUsuarioAppl(WebAppAgregacionNumerales.perfiles.Input request);
        
        [System.ServiceModel.OperationContractAttribute(Action="consultaPerfilesUsuarioAppl", ReplyAction="*")]
        System.Threading.Tasks.Task<WebAppAgregacionNumerales.perfiles.Output> consultaPerfilesUsuarioApplAsync(WebAppAgregacionNumerales.perfiles.Input request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://banrep.gov.co/s3")]
    public partial class s3 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private datosPeticion datosPeticionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public datosPeticion datosPeticion {
            get {
                return this.datosPeticionField;
            }
            set {
                this.datosPeticionField = value;
                this.RaisePropertyChanged("datosPeticion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://banrep.gov.co/s3")]
    public partial class datosPeticion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aplicacionField;
        
        private string usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string aplicacion {
            get {
                return this.aplicacionField;
            }
            set {
                this.aplicacionField = value;
                this.RaisePropertyChanged("aplicacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://banrep.gov.co/s3")]
    public partial class s3Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private datosRespuesta[] datosRespuestaField;
        
        private respuesta respuestaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datosRespuesta", Order=2)]
        public datosRespuesta[] datosRespuesta {
            get {
                return this.datosRespuestaField;
            }
            set {
                this.datosRespuestaField = value;
                this.RaisePropertyChanged("datosRespuesta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public respuesta respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("respuesta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://banrep.gov.co/s3")]
    public partial class datosRespuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string perfilField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string perfil {
            get {
                return this.perfilField;
            }
            set {
                this.perfilField = value;
                this.RaisePropertyChanged("perfil");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://banrep.gov.co/s3")]
    public partial class respuesta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string descripcionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Input {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://banrep.gov.co/s3", Order=0)]
        public WebAppAgregacionNumerales.perfiles.s3 s3;
        
        public Input() {
        }
        
        public Input(WebAppAgregacionNumerales.perfiles.s3 s3) {
            this.s3 = s3;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Output {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://banrep.gov.co/s3", Order=0)]
        public WebAppAgregacionNumerales.perfiles.s3Response s3Response;
        
        public Output() {
        }
        
        public Output(WebAppAgregacionNumerales.perfiles.s3Response s3Response) {
            this.s3Response = s3Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ExecutePortTypeChannel : WebAppAgregacionNumerales.perfiles.ExecutePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ExecutePortTypeClient : System.ServiceModel.ClientBase<WebAppAgregacionNumerales.perfiles.ExecutePortType>, WebAppAgregacionNumerales.perfiles.ExecutePortType {
        
        public ExecutePortTypeClient() {
        }
        
        public ExecutePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ExecutePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecutePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ExecutePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WebAppAgregacionNumerales.perfiles.Output consultaPerfilesUsuarioAppl(WebAppAgregacionNumerales.perfiles.Input request) {
            return base.Channel.consultaPerfilesUsuarioAppl(request);
        }
        
        public System.Threading.Tasks.Task<WebAppAgregacionNumerales.perfiles.Output> consultaPerfilesUsuarioApplAsync(WebAppAgregacionNumerales.perfiles.Input request) {
            return base.Channel.consultaPerfilesUsuarioApplAsync(request);
        }
    }
}
