export interface ItemFlatNode {
    name?: string;
    level?: number;
    Id_NodoContable?: number;
    Id_NodoContablePadre?: number;
    Desc_NodoContablePadre?: string;
    Sk_RCNumeralCambiario?: number;
    idnumeralcco?: string;
    formulacion?: any[];
    expandable?: boolean;
    childs?: any;
    cbEliminado?: boolean;
    fechaEliminado?: string;
    Sk_NodoContable?: number;
    orden?: number;
    date?: string;
    currency?: number;
    cut1?:number;
    cut2?:number;
    cut3?:number;
    cut4?:number;
    cut5?:number;
    cut6?:number;
    cut7?:number;
    cut8?:number;
    cut9?:number;
    cut10?:number;
    cut11?:number;
    cut12?:number;
  }